[build]
  base = "client"
  publish = "build"
  command = "CI= npm run build"

[functions]
  directory = "server/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200
